spring:
  application:
    name: spring-app
  
  # Database Connection Configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/database}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

    hikari:
      initializationFailTimeout: 60000   # Wait DB Configuration for 60s
      connectionTimeout: 30000           # Connection Timeout

  # Flyway Configuration
  flyway:
    enabled: true
    connect-retries: 10
    connect-retries-interval: 5s

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate   # Make JPA not Edit Tables(Flyway will involve)
    show-sql: true     # Show Queries on Console

# Actuator (Application Health Check) Configuration
management:
  endpoint:
    health:
      probes:
        enabled: true  # K8s Probe(Liveness/Readiness) Function
  endpoints:
    web:
      exposure:
        include: health, metrics, conditions, beans
  metrics:
    tags:
      application: ${spring.application.name}
  otlp:
    metrics:
      export:
        url: http://otel-collector.otel-system.svc.cluster.local:4318/v1/metrics
        step: 15s  # Collect Metrics for 15s (CPU/NW Load Management)

server:
  shutdown: graceful
