spring:
  application:
    name: spring-app
  
  # Database Connection Configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/database}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate   # Make JPA not Edit Tables(Flyway will involve)
    show-sql: true     # Show Queries on Console

# Actuator (Application Health Check) Configuration
management:
  endpoint:
    health:
      probes:
        enabled: true  # K8s Probe(Liveness/Readiness) Function
  endpoints:
    web:
      exposure:
        include: health, prometheus # Enable Browser/K8s Access to /actuator/health

server:
  shutdown: graceful
